name: google official document mvvm

on:
  push:
    branches:
      - main
      - google-official-document-mvvm
  pull_request:
    branches:
      - main
      - google-official-document-mvvm


jobs:
  # Run tests - Jobs
  test:
    name: Run Tests for Google Official Document MVVM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.2
      - run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test
